add docu
ls1intum/artemis-ios-core-modules pull request #11
Opened 2023-07-20 15:44 UTC by sven0311

add some more docu

2023-07-20 17:55 UTC, terlan98 approved these changes
The documentation looks good 👍 

I have a non-blocking suggestion: I think it would be useful to add a list of clients along with their repository links and a short description to clarify the apps that are referred to throughout the documentation (`App`, `Themis`, and `Exam Checker`).

I would add something like this right before the 'Modules Overview':

> The package is currently used by the following iOS clients:
> - [Artemis iOS App](https://github.com/ls1intum/artemis-ios) (referred to as the `App`) – Native iOS application for Artemis
> - [Artemis Exam Participation Checker App](https://github.com/ls1intum/ArtemisExamChecker) (referred to as the `Exam Checker`) – an iPad app designed to streamline the process of checking student attendance during on-site exams conducted with the Artemis platform
> - [Themis](https://github.com/ls1intum/Themis)– an iPad app that provides a comprehensive and optimized way for tutors to assess student submissions on the go.

2023-07-21 08:15 UTC, nityanandaz reviewed
I think, shorter lines make tracking changes easier :)

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Common Utility subsystem provides essential utility functions, encompassing a network state wrapper, logging functionality, and date formatting. Almost all other `Core Module`s extensively utiliz
```suggestion
The Common Utility subsystem provides essential utility functions, encompassing a network state wrapper, logging functionality, and date formatting.
Almost all other `Core Module`s extensively utilize this subsystem.
Furthermore, all clients, including `App`, `Exam Checker`, and `Themis`, use this subsystem.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Shared Models subsystem houses all the Artemis domain models required by any of the clients. It includes computed properties with design elements for domain objects, such as the exercise icon, va
```suggestion
The Shared Models subsystem houses all the Artemis domain models required by any of the clients.
It includes computed properties with design elements for domain objects, such as the exercise icon, varying based on the exercise type.
This subsystem is crucial for network communication and its data encryption.
It also ensures consistency and efficiency in data handling across different clients. All clients within the system utilize the Shared Models subsystem.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The User Session Store subsystem stores user-session-related data, encompassing login data and push notification keys. Additionally, it houses configurations about the Artemis instances and maintains
```suggestion
The User Session Store subsystem stores user-session-related data, encompassing login data and push notification keys.
Additionally, it houses configurations about the Artemis instances and maintains a record of the selected instance.
It is important to note that this subsystem is exclusively utilized within the `Core Module`, with no direct usage by any client.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The API Client subsystem is a lightweight API client built upon Apple's URLSession. It provides a straightforward method for sending REST requests and supports the content-types 'application/json' an
```suggestion
The API Client subsystem is a lightweight API client built upon Apple's URLSession.
It provides a straightforward method for sending REST requests and supports the content-types 'application/json' and 'multipart/form-data'.
This subsystem is responsible for encrypting requests and decryption of responses, ensuring secure data transmission.
Additionally, it handles logging and some aspects of error handling, contributing to the system's robustness.
The API Client also includes a simple STOMP web socket client, facilitating real-time communication.
The API Client subsystem is critical for all other subsystems that necessitate network communication.
Its role is to ensure seamless and efficient data exchange within the system, enhancing its overall functionality and performance.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Shared Services subsystem operates with the API Client to deliver service functionality to all other subsystems. This approach ensures that common API calls are not repetitively implemented acros
```suggestion
The Shared Services subsystem operates with the API Client to deliver service functionality to all other subsystems.
This approach ensures that common API calls are not repetitively implemented across different subsystems, promoting code reuse and efficiency.
The subsystem comprises an *AccountService*, *CourseService*, and *ExerciseService*, each providing the necessary calls for their respective services.
The `App` and `Themis` clients extensively utilize this subsystem.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Artemis Markdown subsystem provides a MarkdownView, a crucial component for rendering the partially custom markdown Artemis utilizes. This subsystem is adept at handling and displaying this custo
```suggestion
The Artemis Markdown subsystem provides a MarkdownView, a crucial component for rendering the partially custom markdown Artemis utilizes. This subsystem is adept at handling and displaying this custom markdown.
Currently, the `App` exclusively employs this module to display lecture descriptions or messages within the instant message feature.
This selective use may expand in the future as the system evolves.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Login subsystem manages the authentication flow of Artemis, providing both the user interface for login and the corresponding service layer. It facilitates institution selection, enabling users t
```suggestion
The Login subsystem manages the authentication flow of Artemis, providing both the user interface for login and the corresponding service layer.
It facilitates institution selection, enabling users to switch between different Artemis instances.
All three clients, `App`, `Exam Checker`, and `Themis`, employ this subsystem.
Further, the login subsystem utilizes the User Session Store to retain authentication information.
```

2023-07-21 08:15 UTC, nityanandaz commented on README.md
> +The Artemis Profile Info subsystem primarily supports the Login subsystem by verifying the compatibility of the chosen Artemis instance with the client. This subsystem is service-oriented and does no
```suggestion
The Artemis Profile Info subsystem primarily supports the Login subsystem by verifying the compatibility of the chosen Artemis instance with the client.
This subsystem is service-oriented and does not incorporate any user interface components.
```

2023-07-21 10:55 UTC, terlan98 requested changes
I found a few sentences that can be split into new lines (as suggested by Nityananda). The rest looks good.

2023-07-21 10:55 UTC, terlan98 commented on README.md
> +The Account subsystem manages user account operations. It provides the functionality to view account information and log out of the current user.
```suggestion
The Account subsystem manages user account operations. 
It provides the functionality to view account information and log out of the current user.
```

2023-07-21 10:55 UTC, terlan98 commented on README.md
> +The Artemis Markdown subsystem provides a MarkdownView, a crucial component for rendering the partially custom markdown Artemis utilizes. This subsystem is adept at handling and displaying this custo
```suggestion
The Artemis Markdown subsystem provides a MarkdownView, a crucial component for rendering the partially custom markdown Artemis utilizes. 
This subsystem is adept at handling and displaying this custom markdown.
```

2023-07-21 11:06 UTC, terlan98 approved these changes
Looks good 👍 Thanks for addressing my comments

2023-07-25 07:53 UTC, nityanandaz approved these changes
Thanks

2023-07-25 07:53 UTC, nityanandaz commented on README.md
> +It also ensures consistency and efficiency in data handling across different clients. All clients within the system utilize the Shared Models subsystem.
```suggestion
It also ensures consistency and efficiency in data handling across different clients.
All clients within the system utilize the Shared Models subsystem.
```

2023-07-25 10:03 UTC, merged